const skills = [
    "python",
    "java",
    "javascript",
    "react",
    "node",
    "express",
    "mongodb",
    "mysql",
    "postgresql",
    "docker",
    "kubernetes",
    "aws",
    "cloud",
    "terraform",
    "jenkins",
    "git",
    "github",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "pandas",
    "numpy",
    "sql",
    "html",
    "css",
    "rest api"
];

module.exports = skills;